Snips.addText("de", :error_no_dates, "Ich konnte Start- und Enddatum nicht verstehen")
Snips.addText("de", :error_no_devices, "Ich konnte die Geräte nicht aus der Konfiguartionsdatei lesen!")
Snips.addText("de", :error_device_config, "Ich konnte die Geräte nicht konfigurieren!")
Snips.addText("de", :i_start_from, "Ich starte die Automatisierung am")
Snips.addText("de", :until, "bis")
Snips.addText("de", :ask_device_1, "Soll")
Snips.addText("de", :ask_device_2, "automatisch gesteuert werden?")
Snips.addText("de", :skipped, "wird nicht gesteuert")
Snips.addText("de", :is_on, "Die Hausautomatisierung ist programmiert!")

Snips.addText("de", :ask_end, "Soll die Programmierung der Hausautomatisierung gelöscht werden!")
Snips.addText("de", :all_deleted, "OK. Alle Programmierungen der Hausautomatisierung sind gelöscht!")
Snips.addText("de", :continue, "Abbruch. Die Hausautomatisierung wird nicht gelöscht!")

Snips.addText("de", :i_can, "Ich konnte")
Snips.addText("de", :not_config, "nicht konfigurieren!")
