Snips.addText("de", :error_no_dates, "Ich konnte Start- und Enddatum nicht verstehen")
Snips.addText("de", :error_no_profile, "Ich konnte nicht verstehen, welches Profil ich verwenden soll!")
Snips.addText("de", :error_no_devices, "Ich konnte die Geräte nicht aus der Konfiguartionsdatei lesen!")
Snips.addText("de", :error_device_config, "Ich konnte die Geräte nicht konfigurieren!")
Snips.addText("de", :i_start_from, "Ich starte die Automatisierung am")
Snips.addText("de", :until, "bis")
Snips.addText("de", :ask_device_1, "Soll")
Snips.addText("de", :ask_device_2, "automatisch gesteuert werden?")
Snips.addText("de", :skipped, "wird nicht gesteuert")
Snips.addText("de", :is_on, "Die Hausautomatisierung ist programmiert!")

Snips.addText("de", :ask_end, "Soll die Programmierung der Hausautomatisierung gelöscht werden!")
Snips.addText("de", :all_deleted, "OK. Alle Programmierungen der Hausautomatisierung sind gelöscht!")
Snips.addText("de", :continue, "Abbruch. Die Hausautomatisierung wird nicht gelöscht!")

Snips.addText("de", :i_can, "Ich konnte")
Snips.addText("de", :not_config, "nicht konfigurieren!")



Snips.addText("en", :error_no_dates, "I was not able to understand a start or end date")
Snips.addText("en", :error_no_profile, "I did not recognise a profile to use")
Snips.addText("en", :error_no_devices, "I was not able to find the devices in the config file")
Snips.addText("en", :error_device_config, "I was not able to configure the devices")
Snips.addText("en", :i_start_from, "I will start to control the devices at")
Snips.addText("en", :until, "until")
Snips.addText("en", :ask_device_1, "Shall")
Snips.addText("en", :ask_device_2, "controlled?")
Snips.addText("en", :skipped, "will not be controlled")
Snips.addText("en", :is_on, "The automation is scheduled!")
Snips.addText("en", :ask_end, "Shall I delete all schedules?")
Snips.addText("en", :all_deleted, "OK. I will delete all schedules")
Snips.addText("en", :continue, "Exit - the schedules will not be deleted")
Snips.addText("en", :i_can, "I can")
Snips.addText("en", :not_config, "not configure!")
