site_name:           ADoSnipsTemplate
repo_url:            https://github.com/andreasdominik/ADoSnipsTemplate.git
site_description:    Description
site_author:         Andreas Dominik
theme:               readthedocs

markdown_extensions:
    - codehilite
    - extra
    - tables
    - fenced_code
#    - mdx_math # For LaTeX

extra_css:
    - assets/Documenter.css

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
  - Introduction: index.md
  - Installation: inst.md
  - SnipsHermesQnD: shqd.md
  - Skills: makeskill.md
  - SnipsHermesQnd API:
      - Hermes: api/hermes.md
      - MQTT: api/mqtt.md
      - Dialogues: api/dialogues.md
      - config.ini: api/ini.md
      - Slots: api/slots.md
      - Utilities: api/util.md
  - License: LICENSE.md
